#!/usr/bin/env bash
set -euo pipefail

trap 'echo "[ERROR] $0 failed at line $LINENO" >&2' ERR

# -----------------------------------------------------------------------------
# Restore host scheduling policy after setup_docker_bench_cpuset_full.sh.
#
# This restores broad CPU and NUMA-node access to:
#   - init.scope
#   - system.slice
#   - user.slice
#   - bench.slice
#
# It intentionally does not kill Docker containers. Stop benchmark containers
# before restoring for the cleanest state.
# -----------------------------------------------------------------------------

BACKUP_DIR="${BACKUP_DIR:-/run/grace_docker_cpuset_backup}"
ROOT_CG="/sys/fs/cgroup"

SCRIPT_DIR="$(cd -- "$(dirname -- "${BASH_SOURCE[0]}")" && pwd)"
DEFAULT_REPO_ROOT="$(cd -- "${SCRIPT_DIR}/../.." && pwd)"
REPO_ROOT="${REPO_ROOT:-$DEFAULT_REPO_ROOT}"

TARGET_UNITS=("init.scope" "system.slice" "user.slice")
DEFAULT_BENCH_SLICE="bench.slice"

die() {
  echo "[ERROR] $*" >&2
  exit 1
}

warn() {
  echo "[WARN] $*" >&2
}

info() {
  echo "[INFO] $*"
}

ok() {
  echo "[OK] $*"
}

need_root() {
  if [[ "$(id -u)" -ne 0 ]]; then
    die "Run this script as root: sudo $0"
  fi
}

set_unit_allowed() {
  local unit="$1"
  local cpus="$2"
  local mems="$3"

  info "Restoring ${unit}: AllowedCPUs=${cpus}, AllowedMemoryNodes=${mems}"
  systemctl set-property --runtime "$unit" \
    "AllowedCPUs=${cpus}" \
    "AllowedMemoryNodes=${mems}" >/dev/null || warn "Could not restore ${unit}"
}

main() {
  need_root
  command -v systemctl >/dev/null 2>&1 || die "systemctl not found."

  local all_cpus all_mems bench_slice
  all_cpus="$(cat /sys/devices/system/cpu/online)"
  all_mems="$(cat /sys/devices/system/node/online 2>/dev/null || echo 0)"
  bench_slice="$DEFAULT_BENCH_SLICE"

  if [[ -f "${BACKUP_DIR}/state.env" ]]; then
    # shellcheck disable=SC1090
    source "${BACKUP_DIR}/state.env"
    all_cpus="${ALL_CPUS:-$all_cpus}"
    all_mems="${ALL_MEMS:-$all_mems}"
    bench_slice="${BENCH_SLICE:-$DEFAULT_BENCH_SLICE}"
  else
    warn "No backup state found at ${BACKUP_DIR}/state.env. Using current online CPU/node sets."
  fi

  echo "============================================================"
  echo "Restoring Docker benchmark cpuset isolation"
  echo "============================================================"
  echo "Restored CPUs : ${all_cpus}"
  echo "Restored MEMs : ${all_mems}"
  echo "Bench slice   : ${bench_slice}"
  echo

  # Restore broad access to normal host slices/scopes.
  for unit in "${TARGET_UNITS[@]}"; do
    set_unit_allowed "$unit" "$all_cpus" "$all_mems"
  done

  # Restore broad access to bench.slice too, then stop/remove runtime unit if idle.
  set_unit_allowed "$bench_slice" "$all_cpus" "$all_mems"

  echo
  echo "Attempting to stop ${bench_slice}."
  echo "This may fail if a Docker container is still running under it."
  systemctl stop "$bench_slice" >/dev/null 2>&1 || warn "Could not stop ${bench_slice}; stop benchmark containers and retry if needed."

  # Remove runtime unit file created by setup script.
  local bench_slice_unit="/run/systemd/system/${bench_slice}"
  if [[ -f "$bench_slice_unit" ]]; then
    rm -f "$bench_slice_unit"
    systemctl daemon-reload
  fi

  # Remove repo-local generated Docker cpuset metadata.
  #
  # These files are generated by setup_docker_bench_cpuset_full.sh and are used by
  # docker/run_cuda*.sh to automatically add --cgroup-parent/--cpuset flags.
  # After restore, they must be removed so future Docker runs do not use stale
  # benchmark-cpuset settings.
  local generated_dir="${REPO_ROOT}/docker/.generated"
  local generated_env="${generated_dir}/docker_cpuset.env"
  local generated_run="${generated_dir}/docker_run_grace.sh"

  if [[ -f "${generated_env}" ]]; then
    info "Removing generated Docker cpuset env: ${generated_env}"
    rm -f "${generated_env}"
  fi

  if [[ -f "${generated_run}" ]]; then
    info "Removing generated Docker run script: ${generated_run}"
    rm -f "${generated_run}"
  fi

  if [[ -d "$BACKUP_DIR" ]]; then
    rm -rf "$BACKUP_DIR"
  fi

  echo
  echo "Verification:"
  for unit in "${TARGET_UNITS[@]}" "$bench_slice"; do
    echo
    echo "${unit}:"
    systemctl show "$unit" -p AllowedCPUs -p AllowedMemoryNodes 2>/dev/null || true
  done

  echo
  ok "Host cpuset policy restored."
}

main "$@"